alias ls='eza --icons --group-directories-first'
alias open='xdg-open'
alias find='fd'
alias grep='/usr/bin/grep'
# alias grep='rg'
alias gdiff='git difftool --no-symlinks --dir-diff'
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'
alias mkreport='typst init @local/my_template:1.0.0'
alias juniormnt='sftpman mount junior && cd /mnt/sshfs/junior'
alias juniorumnt='cd ~ && sftpman umount junior'
alias vroom='sftpman mount vroom && cd /mnt/sshfs/vroom'
alias unvroom='cd ~ && sftpman umount vroom'
alias gz='QT_QPA_PLATFORM=xcb gazebo.gz'
alias dockup='docker compose -f ~/Devel/vroomitor/docker-compose.yml up -d --build'
alias dockdown='docker compose -f ~/Devel/vroomitor/docker-compose.yml down'
